container_image = docker://sncromp/tabbysd:0
universe = container
executable = reclaim_trials.sh

log = logs/reclaim_$(Cluster)_$(Process).log
error = logs/reclaim_$(Cluster)_$(Process).err
output = logs/reclaim_$(Cluster)_$(Process).out

should_transfer_files = YES
transfer_input_files = /home/cromp/sd-project/structureddata.tar.gz

request_cpus = 1
request_memory = 64GB
request_disk = 100GB
+JobLength = "short"

queue 1
