container_image = docker://sncromp/tabbysd:0
universe = container
executable = ../run_optuna_worker.sh

dataset = cern
model = icl 
arguments = $(dataset) $(model)

log = logs/optuna_$(model)_$(dataset)_$(Cluster)_$(Process).log
error = logs/optuna_$(model)_$(dataset)_$(Cluster)_$(Process).err
output = logs/optuna_$(model)_$(dataset)_$(Cluster)_$(Process).out

should_transfer_files = YES
transfer_input_files = /home/cromp/sd-project/structureddata.tar.gz

requirements = (CUDACapability >= 4) && (Target.HasCHTCStaging == True)
request_cpus = 1
request_memory = 64GB
request_disk = 100GB
request_gpus = 1
require_gpus = (GlobalMemoryMB >= 48000)
+WantGPULab = true
+GPUJobLength = "short"

queue 3
